/**
 * Sanity Migration Engine v3 — TypeScript Type Generator
 *
 * Reads sanity-mirror/schema-map.json (produced by introspect-schemas.ts)
 * and generates:
 *
 *   sanity-mirror/generated-types.ts
 *
 * Types are fully annotated with JSDoc comments and follow the existing
 * project convention for Sanity document types.
 *
 * Runs with: tsx scripts/sanity/generate-types.ts
 */

import * as fs from "fs";
import {
  SCHEMA_MAP_FILE,
  SCHEMAS_META_DIR,
  GENERATED_TYPES_FILE,
  ensureDir,
  log,
} from "./config";
import * as path from "path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface FieldMeta {
  name: string;
  type: string;
  required: boolean;
  isArray: boolean;
}

interface SchemaMeta {
  name: string;
  type: "document" | "object";
  fields: FieldMeta[];
  references: string[];
  assets: string[];
}

interface CompactSchemaMeta {
  fields: string[];
  references: string[];
  assets: string[];
}

type CompactSchemaMap = Record<string, CompactSchemaMeta>;

// ---------------------------------------------------------------------------
// Sanity → TypeScript type mapping
// ---------------------------------------------------------------------------
const TYPE_MAP: Record<string, string> = {
  string: "string",
  text: "string",
  number: "number",
  boolean: "boolean",
  date: "string", // ISO date string
  datetime: "string",
  url: "string",
  email: "string",
  slug: "SanitySlug",
  image: "SanityImage",
  file: "SanityFile",
  reference: "SanityReference",
  object: "Record<string, unknown>",
  array: "unknown[]",
  block: "SanityBlock",
  color: "SanityColor",
};

function mapType(
  fieldName: string,
  sanityType: string,
  isArray: boolean,
  assets: string[],
  references: string[],
): string {
  let tsType: string;

  if (assets.includes(fieldName)) tsType = "SanityImage";
  else if (references.includes(fieldName)) tsType = "SanityReference";
  else tsType = TYPE_MAP[sanityType] ?? "unknown";

  return isArray ? `${tsType}[]` : tsType;
}

// ---------------------------------------------------------------------------
// Shared Sanity primitive types header
// ---------------------------------------------------------------------------
const HEADER = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: scripts/sanity/generate-types.ts
 * Source: sanity-mirror/schema-map.json
 *
 * Regenerate with: npm run sanity:generate-types
 */

// ---------------------------------------------------------------------------
// Sanity Primitive Types
// ---------------------------------------------------------------------------

export interface SanitySlug {
  current: string;
  _type: "slug";
}

export interface SanityImageRef {
  _ref: string;
  _type: "reference";
}

export interface SanityImage {
  _type: "image";
  asset?: SanityImageRef;
  hotspot?: {
    x: number;
    y: number;
    height: number;
    width: number;
  };
  crop?: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
}

export interface SanityFile {
  _type: "file";
  asset?: SanityImageRef;
}

export interface SanityReference {
  _type: "reference";
  _ref: string;
}

export interface SanityBlock {
  _type: "block";
  _key: string;
  style?: string;
  children?: Array<{
    _type: "span";
    _key: string;
    text: string;
    marks?: string[];
  }>;
  markDefs?: unknown[];
}

export interface SanityColor {
  hex: string;
  alpha: number;
  hsl?: { h: number; s: number; l: number; a: number };
  hsv?: { h: number; s: number; v: number; a: number };
  rgb?: { r: number; g: number; b: number; a: number };
}

`;

// ---------------------------------------------------------------------------
// Generate interface for a single schema type
// ---------------------------------------------------------------------------
function generateInterface(
  name: string,
  meta: FieldMeta[],
  assets: string[],
  references: string[],
  isDocument: boolean,
): string {
  const exportName = toInterfaceName(name);
  const lines: string[] = [];

  lines.push(
    `/** Sanity ${isDocument ? "document" : "object"} type: "${name}" */`,
  );
  lines.push(`export interface ${exportName} {`);

  if (isDocument) {
    lines.push(`  _id: string;`);
    lines.push(`  _type: "${name}";`);
    lines.push(`  _rev?: string;`);
    lines.push(`  _createdAt?: string;`);
    lines.push(`  _updatedAt?: string;`);
  }

  for (const field of meta) {
    const tsType = mapType(
      field.name,
      field.type,
      field.isArray,
      assets,
      references,
    );
    const optional = !field.required ? "?" : "";
    lines.push(`  ${field.name}${optional}: ${tsType};`);
  }

  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function toInterfaceName(typeName: string): string {
  return (
    typeName.charAt(0).toUpperCase() +
    typeName.slice(1).replace(/_([a-z])/g, (_, c: string) => c.toUpperCase()) +
    "Document"
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  if (!fs.existsSync(SCHEMA_MAP_FILE)) {
    log(
      "schema-map.json not found. Run npm run sanity:introspect first.",
      "error",
    );
    process.exit(1);
  }

  const compactMap = JSON.parse(
    fs.readFileSync(SCHEMA_MAP_FILE, "utf-8"),
  ) as CompactSchemaMap;

  log(`Generating types for: ${Object.keys(compactMap).join(", ")}`);

  let output = HEADER;

  // Load detailed field metadata from per-type schema files
  for (const [typeName, compact] of Object.entries(compactMap)) {
    const detailFile = path.join(SCHEMAS_META_DIR, `${typeName}.json`);

    let fields: FieldMeta[] = [];
    let isDocument = true;

    if (fs.existsSync(detailFile)) {
      const detail = JSON.parse(
        fs.readFileSync(detailFile, "utf-8"),
      ) as SchemaMeta;
      fields = detail.fields;
      isDocument = detail.type === "document";
    } else {
      // Fallback: use field names from compact map, all optional strings
      fields = compact.fields.map((f) => ({
        name: f,
        type: compact.assets.includes(f) ? "image" : "string",
        required: false,
        isArray: false,
      }));
    }

    output += generateInterface(
      typeName,
      fields,
      compact.assets,
      compact.references,
      isDocument,
    );
  }

  // Generate union type of all document types
  const docNames = Object.entries(compactMap)
    .filter(() => true) // include all
    .map(([n]) => toInterfaceName(n));

  output += `// ---------------------------------------------------------------------------\n`;
  output += `// Union type of all document types\n`;
  output += `// ---------------------------------------------------------------------------\n\n`;
  output += `export type AnyDocument =\n`;
  output += docNames.map((n) => `  | ${n}`).join("\n");
  output += `;\n\n`;

  // _type string union
  output += `export type DocumentType = AnyDocument["_type"];\n`;

  ensureDir(path.dirname(GENERATED_TYPES_FILE));
  fs.writeFileSync(GENERATED_TYPES_FILE, output, "utf-8");

  log(`\n✓ TypeScript types written → ${GENERATED_TYPES_FILE}`);
  console.log(
    `  Types generated: ${Object.keys(compactMap).length} interface(s)`,
  );
  console.table(
    Object.keys(compactMap).map((n) => ({
      type: n,
      interface: toInterfaceName(n),
    })),
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
